# Generated by Django 5.1.1 on 2024-10-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_carmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
