# Generated by Django 5.1.1 on 2024-10-30 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_carmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='purchased_by',
            field=models.ManyToManyField(blank=True, related_name='purchased_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
