# Generated by Django 5.1.1 on 2024-10-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_remove_carmodel_user_carmodel_purchased_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='purchased_by',
        ),
    ]
